services:
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: very_secret
      MYSQL_DATABASE: lending_db
      MYSQL_USER: lending_user
      MYSQL_PASSWORD: lending_password
    ports:
      - "3316:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
